name: Android CI

on:
  push:
    branches:
    - '*-FOSS'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install NDK
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build with Gradle
      run: ./gradlew assemblePlayFossProdRelease

    - name: Get version
      id: get-version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/heads/}

    - name: Sign APKs
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
      run: |
        echo "${KEYSTORE_BASE64}" | base64 -d > apksign.keystore
        for apk in app/build/outputs/apk/playFossProd/release/*-unsigned-*.apk; do
        jarsigner -keystore apksign.keystore -storepass ${KEYSTORE_PASS} -signedjar "${apk/-unsigned-/-signed-}" "${apk}" apksign
        done
        rm apksign.keystore

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ steps.get-version.outputs.VERSION }}"
        release_name: "Signal ${{ steps.get-version.outputs.VERSION }}"
        draft: false
        prerelease: false

    - name: Get Universal APK Filename
      id: get-universal-filename
      run: echo ::set-output name=FILENAME::$(basename $(ls -1 app/build/outputs/apk/playFossProd/release/*-universal-*-signed-*.apk) )

    - name: Upload Universal APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "app/build/outputs/apk/playFossProd/release/${{ steps.get-universal-filename.outputs.FILENAME }}"
        asset_name: ${{ steps.get-universal-filename.outputs.FILENAME }}
        asset_content_type: application/vnd.android.package-archive
